### ISSUE TITLE
Linear Algebra download link misdirected

### ISSUE THREAD

**Issue by DaveGunn** [IDPF/epub3-samples#1]
I just noticed that the link to download the Linear Algebra title on the samples page (https://github.com/IDPF/epub3-samples#linear-algebra) appears to be pointing at the Kusamakura title by accident.

Dave

**Comment by mattgarrish** [comment]
Thanks, Dave. I just pushed a fix with the correct link.

**Comment by thiagoeec** [comment]
Matt,

The link for Linear Algebra sample is still pointing to the wrong file (Kusamakura).

**Comment by mattgarrish** [comment]
Ah, thanks! When we moved the samples list and feature matrix to github pages it looks like a pre-fix version of the html got used. I've updated again...
