### ISSUE TITLE
whats the best software to make an epub ?

### ISSUE THREAD

**Issue by alihariri** [IDPF/epub3-samples#12]
i find indesign so hard to build creative reflowable epub . so is there any replacement ?

**Comment by RachelComerford** [comment]
I prefer ground up builds in xhtml rather than starting in indesign, especially if you can establish a standardized xml schema and a baseline CSS to work from

**Comment by NERogers** [comment]
Are you using Indesign as a publisher?

**Comment by rickj** [comment]
If you are looking for template driven (customization available) easy to use, WCAG 2.0 AA conformance (including interactives), I have to point out https://www.vitalsource.com/vcs .  Yeah, it's my company!

**Comment by alihariri** [comment]
@RachelComerford the problem is my programming skills. im a graphic designer . and ofcourse i can change a color in html . but i can't build an epub in xhtml from the start point. so indesign helps to build a foundation and then i can make small changes i want with editors like calibre .

**Comment by alihariri** [comment]
@NERogers yes in paper prints . and in digital versions . all in indesign

**Comment by alihariri** [comment]
@rickj hey thank you for offer . i visited your webpage . its quite intresting . i asked for a demo . i hope you accept the my request . and i saw you have webinars . are they free ?

**Comment by nastarovia** [comment]
Probably, the best choice for having a well structured epub3 from scratch without the worries of coding is create the source text in markdown and then convert it to epub using pandoc

**Comment by alihariri** [comment]
@nastarovia tnx . it helps alot . im working on it . markdown is all new to me

**Comment by Tuanis** [comment]
I also want to create a file (I guess Epub, although I'm completely new at this), to combine a text (english, spanish or hebrew), and an audio (or video) of a person reading and explaining the text. I want read-along maybe with highliting of text. Ability to click on text and synchronize the audio/video to that point. Please help me with ideas on software (hopefuly free) and file types, etc. Thanks
