### ISSUE TITLE
incorrect link reference for moby-dick.mo

### ISSUE THREAD

**Issue by jefferydecker** [IDPF/epub3-samples#16]
In your features matrix, the links to moby dick with overlays points to moby-dick.epub instead of moby-dick-mo.epub

**Comment by danielweck** [comment]
It looks fine to me (?)

http://idpf.github.io/epub3-samples/30/samples.html#moby-dick-mo

**Comment by jefferydecker** [comment]
Yes, it looks fine to me now too. My mistake.
