### ISSUE TITLE
How compile an Epub project and test.

### ISSUE THREAD

**Issue by dominicfollett** [IDPF/epub3-samples#4]
Hi 

I very new to Epubs, I used the following command for the tress example (I use ubuntu): 

pandoc -f html -t epub3 -o output.epub c1.xhtml c2.xhtml package.opf  titlepage.xhtml style.css script/*

and then I tried to view the epub in the chrome readium app, and the javascript appears as text. 

Am I supposed to do this differently? I can't find any explanation of how these project files should be compiled. Your help would be most welcome.

**Comment by mattgarrish** [comment]
You can use the shell and batch scripts at the root of the repository to build the samples using epubcheck. For an individual sample, you would do:

pack-single.sh 30/trees

You can also download pre-built versions of the samples from:

http://idpf.github.io/epub3-samples/samples.html

**Comment by mattgarrish** [comment]
I've updated the project readme to include compiling instructions, so closing this issue.

**Comment by dominicfollett** [comment]
Thanks, Matt.
