### ISSUE TITLE
Example `haruko-ahl` does not validate (Region-Based Navigation)

### ISSUE THREAD

**Issue by titusz** [IDPF/epub3-samples#5]
With epubcheck 4.0.0 which is claims to support "EPUB Region-Based Navigation 1.0" I get errors like:

```
Undefined property: 'panel'.
Undefined property: 'ballon'.
```

Anyone knows if this is an issue with the sample or with epubcheck 4.0?

**Comment by mattgarrish** [comment]
It's an issue with the initial 4.0 release. I've already reported that the properties aren't being validated and a fix is coming in the 4.0.1 release: https://github.com/IDPF/epubcheck/issues/587

**Comment by titusz** [comment]
Wow that was fast.... great news... and thank you... looking forward to experiment with Region-Based Navigation
