### ISSUE TITLE
Attribution within an XHTML content document?

### ISSUE THREAD

**Issue by murata2makoto** [IDPF/epub3-samples#6]
According to the README.md, "As a contributor, you are able to specify attribution metadata only in the sample's package file."  Does this mean that an XHTML or SVG content document cannot describe the owner, copyright, CC by SA, mail address, etc?

**Comment by mattgarrish** [comment]
No, I believe it was addressing that IDPF wouldn't credit individuals or organizations outside of the epub. You can include at the content document level, but a reading system won't surface it which is why only the package is listed as a way of getting your info out.

**Comment by mattgarrish** [comment]
Closing as the readme will need to be rewritten by the CG maintainers anyway.
