### ISSUE TITLE
incorrect Wasteland download link (obfuscated WOFF)

### ISSUE THREAD

**Issue by danielweck** [IDPF/epub3-samples#7]
http://idpf.github.io/epub3-samples/samples.html
The last link for Wasteland is https://drive.google.com/uc?export=download&id=0B9g8D2Y-6aPLZ0s0cjFaZHJOYms which is the same as the one immediately above (non-obfuscated WOFF)

**Comment by danielweck** [comment]
The download link (Google Drive) is still pointing to the incorrect EPUB. Whoever has direct access to the Google Drive directory listing: could you please find out the correct URL, and update `samples.html` accordingly?
Thanks :)

**Comment by mattgarrish** [comment]
Fixed.
